#!/usr/bin/bash

## only tested on linux, but it should probably work on mac as well. Not a chance of windows unless
## you're using cygwin, with which I have no experience.
## doesn't check for clobbering, just reinstalls everything regardless

join_by() { local IFS="$1"; shift; echo "$*"; }

## check for this software. Only stack is essential
stack=$(which stack 2>/dev/null) 
fig=$(which figlet 2>/dev/null)
cow=$(which cowsay 2>/dev/null)
lol=$(which lolcat 2>/dev/null)
dot=$(which dot 2>/dev/null)
cl=$(which clang-format 2>/dev/null)

if [ ! -x "$fig" ]; then
    progs=("${progs[@]}" "figlet ")
fi

if [ ! -x "$cow" ]; then
    progs=("${progs[@]}" " cowsay ")
fi

if [ ! -x "$lol" ]; then
    progs=("${progs[@]}" " lolcat")
fi

if [ -x "$stack" ]; then
    printf "\e[1mstack found\e[0m\n"
    printf "\e[1mrunning tests and building\e[0m\n"
    stack test 
    rc=$?
    if [ "$rc" != 0 ]; then
        printf "\n\e[31mCould not pass all tests. The build has failed\e[0m\n"
        exit "$rc" 
    fi
    printf "\e[1minstalling in %s/.local/bin/\n" "$HOME"
    stack install
    rc=$?
    if [ "$rc" != 0 ]; then
        printf "\nCould not install the executable into %s/.local/bin. 
        \ Please copy it manually into your path\n" "$HOME"
        exit "$rc"
    fi
    printf "\n\e[1mcopying standard libraries to home directory\e[0m\n"

    ## delete old standard libs if they are found
    if [ -x "$HOME"/.microML ]; then
        printf "\n\e[1mremoving old standard library\e[0m\n"
        rm -rf "$HOME"/.microML
    fi
    printf "\n\e[1minstalling standard library\e[0m\n"

    cp -vr src/Libs "$HOME"
    mv "$HOME/Libs" "$HOME/.microML"
    printf "\n\e[1mcopying default .microMLrc to home directory\e[0m\n"

    cp -v utils/microMLrc "$HOME"/.microMLrc
    printf "\n\e[1mfinished!\e[0m\n"

    if [ -n "$progs" ]; then
        len=${#progs[@]}
        if [ "$len" -eq 1 ]; then
            str="${progs[*]}"
        elif [ "$len" -eq 2 ]; then
            str=$(join_by $"&" "${progs[@]}")
        else 
            str=$("figlet, cowsay and lolcat")
        fi
        printf "\e[1mYou can have a more interesting repl if you also install %s\e[0m\n" "$str"
    fi

    if [ ! -x "$dot" ]; then
        printf "\e[1mIf you install \e[32mdot\e[0;1m then you can make callgraphs of your programs.\e[0m\n"
    fi

    if [ ! -x "$cl" ]; then
        printf "\e[1mIf you install \e[32mclang-format\e[0;1m then you can format your C++ code.\e[0m\n"
    fi
else 
    printf "\e[31mCould not find stack in your system path. Please install it using your package
    manager or go to \e[0;1mhttps://docs.haskellstack.org/en/stable/README/\e[0m\n"
fi
