#!/usr/bin/bash

pdflatex=$(which pdflatex)
bibtex=$(which bibtex)
file="$1"
usingMinted=$(ag minted "$file".tex)

## the minted package needs pdflatex to be run with the shell-escape option
## so check for it in the file
if [ -x "$pdflatex" ] && [ -x "$bibtex" ]; then
    if [ "$usingMinted" == "" ]; then
        echo "compiling $file"
        pdflatex "$file".tex
        bibtex "$file".aux
        pdflatex "$file".tex
    else
        echo "minted detected, so using shell escape"
        echo "compiling $file"
        pdflatex -shell-escape "$file".tex
        bibtex "$file".aux
        pdflatex -shell-escape "$file".tex
    fi
fi
